"""
nodes/tools.py — Native LangGraph tool execution node.

Executes standard LangChain tool calls generated by the LLM and
appends the result as a ToolMessage to the state.
"""

import logging
import uuid
from pathlib import Path
from langchain_core.messages import ToolMessage

logger = logging.getLogger(__name__)

def _get_tool_registry() -> dict:
    try:
        from mcp_servers import GLOBAL_TOOL_REGISTRY
        return GLOBAL_TOOL_REGISTRY
    except ImportError as e:
        logger.warning(f"Could not load GLOBAL_TOOL_REGISTRY: {e}")
        return {}

import inspect

async def _execute_tool_func(action_name: str, tool_args: dict, config: dict):
    """Execute a tool and return result. Supports multimodal returns (list of content blocks)."""
    registry = _get_tool_registry()
    func = registry.get(action_name)
    if not func:
        return f"Error: Tool '{action_name}' not found in registry."
    
    try:
        logger.info(f"  -> Executing {action_name}({tool_args})")
        if hasattr(func, "ainvoke"):
            result = await func.ainvoke(tool_args, config=config)
        else:
            result = func(**tool_args)
            if inspect.isawaitable(result):
                result = await result
        logger.info(f"  -> {action_name} completed successfully")
        # Allow true LangChain multimodal blocks to pass through natively
        if isinstance(result, list):
            is_multimodal = len(result) > 0 and isinstance(result[0], dict) and "type" in result[0]
            if is_multimodal:
                return result
                
            # Stringify raw data arrays safely
            import json
            try:
                result_str = json.dumps(result)
            except Exception:
                result_str = str(result)
        else:
            result_str = str(result)
        
        # Scratchpad offloading for large payloads
        if len(result_str) > 4000:
            scratchpad_dir = Path("data/scratchpad")
            scratchpad_dir.mkdir(parents=True, exist_ok=True)
            
            file_id = uuid.uuid4().hex[:8]
            file_name = f"output_{action_name}_{file_id}.md"
            file_path = scratchpad_dir / file_name
            
            file_path.write_text(result_str, encoding="utf-8")
            
            preview = result_str[:500]
            result_str = f"Output exceeded context limits. TRUNCATED. Raw output saved to: {file_path.absolute()}\n\nTop preview:\n{preview}\n\n...[TRUNCATED]...\n\n**If you need the full output, use your `exec_command` tool to run `cat {file_path.absolute()} | grep [keyword]`**"
            
        return result_str
    except Exception as e:
        logger.error(f"  -> {action_name} failed: {e}")
        return f"Error executing {action_name}: {e}"

async def execute_tools_node(state: dict) -> dict:
    """
    Execute tool calls in the last AI message and append the results as ToolMessages.
    """
    logger.info("--- [Node: Execute Tools] ---")
    messages = state.get("messages", [])
    if not messages:
        return {}
    
    last_message = messages[-1]
    # Check if the last message has tool calls
    if not hasattr(last_message, "tool_calls") or not last_message.tool_calls:
        return {}
    
    tool_messages = []
    
    # Tools like exec_command need the thread_id to inject backgrounds
    thread_id = state.get("chat_id", "default_thread")
    config = {"configurable": {
        "thread_id": thread_id,
        "active_model": state.get("active_model")
    }}
    
    for tool_call in last_message.tool_calls:
        action_name = tool_call["name"]
        tool_args = tool_call["args"]
        call_id = tool_call["id"]
        
        result = await _execute_tool_func(action_name, tool_args, config)
            
        tool_messages.append(ToolMessage(content=result, tool_call_id=call_id))
        
    return {"messages": tool_messages}
