"""
nodes/tools.py — Native LangGraph tool execution node.

Executes standard LangChain tool calls generated by the LLM and
appends the result as a ToolMessage to the state.
"""

import logging
import uuid
from pathlib import Path
from langchain_core.messages import ToolMessage

logger = logging.getLogger(__name__)

def _get_tool_registry() -> dict:
    try:
        from mcp_servers import GLOBAL_TOOL_REGISTRY
        return GLOBAL_TOOL_REGISTRY
    except ImportError as e:
        logger.warning(f"Could not load GLOBAL_TOOL_REGISTRY: {e}")
        return {}

import inspect

async def _execute_tool_func(action_name: str, tool_args: dict, config: dict):
    """Execute a tool and return result. Supports multimodal returns (list of content blocks)."""
    registry = _get_tool_registry()
    func = registry.get(action_name)
    if not func:
        return f"Error: Tool '{action_name}' not found in registry."
    
    try:
        if hasattr(func, "ainvoke"):
            result = await func.ainvoke(tool_args, config=config)
        else:
            result = func(**tool_args)
            if inspect.isawaitable(result):
                result = await result
        # Allow true LangChain multimodal blocks to pass through natively
        if isinstance(result, list):
            is_multimodal = len(result) > 0 and isinstance(result[0], dict) and "type" in result[0]
            if is_multimodal:
                return result
                
            # Stringify raw data arrays safely
            import json
            try:
                result_str = json.dumps(result)
            except Exception:
                result_str = str(result)
        else:
            result_str = str(result)
            
        return result_str
    except Exception as e:
        logger.error(f"  -> {action_name} failed: {e}")
        return f"Error executing {action_name}: {e}"

async def execute_tools_node(state: dict) -> dict:
    """
    Execute tool calls in the last AI message and append the results as ToolMessages.
    """
    messages = state.get("messages", [])
    if not messages:
        return {}
    
    last_message = messages[-1]
    # Check if the last message has tool calls
    if not hasattr(last_message, "tool_calls") or not last_message.tool_calls:
        return {}
    
    tool_messages = []
    
    # Tools like exec_command need the thread_id to inject backgrounds
    thread_id = state.get("chat_id", "default_thread")
    config = {"configurable": {
        "thread_id": thread_id,
        "active_model": state.get("active_model")
    }}
    
    ephemeral_outputs = state.get("last_tool_output", []) or []
    if not isinstance(ephemeral_outputs, list):
        ephemeral_outputs = []
        
    for tool_call in last_message.tool_calls:
        action_name = tool_call["name"]
        tool_args = tool_call["args"]
        call_id = tool_call["id"]
        
        result_content = await _execute_tool_func(action_name, tool_args, config)
        
        # If the result isn't multimodal, check for length
        if isinstance(result_content, str) and len(result_content) > 2000:
            ephemeral_outputs.append({
                "tool": action_name,
                "output": result_content
            })
            
            preview = result_content[:500]
            summary_history = f"[Output truncated to save context. Full output is available in ephemeral memory]. Top preview:\n{preview}\n\n...[TRUNCATED]..."
            
            tool_messages.append(ToolMessage(content=summary_history, tool_call_id=call_id))
        else:
            tool_messages.append(ToolMessage(content=result_content, tool_call_id=call_id))
            
    if ephemeral_outputs:
        return {"messages": tool_messages, "last_tool_output": ephemeral_outputs}
    return {"messages": tool_messages}
